[deps.nixpkgs]
commit = "f8c12edfdf2e163768fa5380af3cf99fdd29866d"
sha256 = "1kjbrv26mpgagy4dp30qq81wlk0iplzhqsq5hpdclhnvk5cpwysr"

[builder.rpm.container-image]
image = "fedora"
ref = "latest"

[base-container-image]
ref = "library/fedora@sha256:9c78c69f748953ba8fdb6eb9982e1abefe281d9b931a13f251eb8aec988353de"