[package]
name = "moondog"
version = "0.1.0"
authors = ["Zac Mrowicki <mrowicki@amazon.com>"]
edition = "2018"
publish = false
build = "build.rs"

[dependencies]
reqwest = { version = "0.9", default-features = false, features = [] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
snafu = "0.4"
toml = "0.4"
log = "0.4"
stderrlog = "0.4"

[build-dependencies]
cargo-readme = "3.1"
