[workspace]
members = [
    "api/apiserver",
    "api/apiclient",
    "api/bork",
    "api/early-boot-config",
    "api/netdog",
    "api/sundog",
    "api/schnauzer",
    "api/pluto",
    "api/servicedog",
    "api/host-containers",
    "api/storewolf",
    "api/thar-be-settings",
    "api/settings-committer",
    "api/migration/migrator",
    "api/migration/migration-helpers",

    "api/migration/migrations/v0.3.1/migration-test-remove-motd",
    "api/migration/migrations/v0.3.1/migration-test-add-foo",
    
    "bottlerocket-release",

    "growpart",

    "models",

    "preinit/laika",

    "updater/block-party",
    "updater/signpost",
    "updater/update_metadata",
    "updater/updog",

    "webpki-roots-shim",
]

[profile.release]
debug = true

# This replaces webpki-roots with a shim that reads from the ca-certificates package
[patch.crates-io.webpki-roots]
path = "webpki-roots-shim"
